# syntax=docker.io/docker/dockerfile-upstream:1.27.0
# check=error=true

# Copyright (C) 2026 - present, Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker build --tag juergenzimmermann/buch:2026.10.1-bun -f Dockerfile.bun .
#               ggf. --progress=plain
#               ggf. --no-cache
#
#           Windows:   Get-Content Dockerfile.bun | docker run --rm --interactive hadolint/hadolint:v2.15.1-debian
#           macOS:     cat Dockerfile.bun | docker run --rm --interactive hadolint/hadolint:v2.15.1-debian
#
#           docker debug juergenzimmermann/buch:2026.10.1-bun
#           docker network ls
#           docker save juergenzimmermann/buch:2026.10.1-bun > buch.tar

# https://docs.docker.com/engine/reference/builder/#syntax
# https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md
# https://hub.docker.com/r/docker/dockerfile

ARG BUN_VERSION=1.4.2

FROM oven/bun:${BUN_VERSION}-slim AS dist

WORKDIR /app

# https://docs.docker.com/engine/reference/builder/#run---mounttypebind
RUN --mount=type=bind,source=package.json,target=package.json \
  --mount=type=cache,target=/root/.bun <<EOF
  bun install --production
EOF

FROM dhi.io/bun:${BUN_VERSION}-debian13 AS final

WORKDIR /opt/app

ARG BUN_UID=65523 \
    BUN_GID=65523

USER ${BUN_UID}:${BUN_GID}

COPY --chown=${BUN_UID}:${BUN_GID} package.json ./
COPY --from=dist --chown=${BUN_UID}:${BUN_GID} /app/node_modules ./node_modules
COPY --chown=${BUN_UID}:${BUN_GID} src ./src

# Anzeige bei "docker inspect ..."
# https://specs.opencontainers.org/image-spec/annotations
# https://spdx.org/licenses
# MAINTAINER ist deprecated https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
LABEL org.opencontainers.image.title="buch" \
  org.opencontainers.image.description="Appserver buch mit 'hardened' Basis-Image Bun und Debian 13" \
  org.opencontainers.image.version="2026.10.1-trixie" \
  org.opencontainers.image.licenses="GPL-3.0-or-later" \
  org.opencontainers.image.authors="Juergen.Zimmermann@h-ka.de"

EXPOSE 3000

# Binding fuer alle Netzwerk-Interfaces
ENV BUN_BIND_HOST=0.0.0.0

# Bei CMD statt ENTRYPOINT kann das Kommando bei "docker run ..." ueberschrieben werden
# "Array Syntax" damit auch <Strg>C funktioniert
ENTRYPOINT ["bun", "run", "src/index.mts"]
