# syntax=docker.io/docker/dockerfile-upstream:1.26.0
# check=error=true

# Copyright (C) 2024 - present, Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker build --tag juergenzimmermann/buch:2026.10.1-alpine -f Dockerfile.alpine .
#               ggf. --progress=plain
#               ggf. --no-cache
#
#           Windows:   Get-Content Dockerfile.alpine | docker run --rm --interactive hadolint/hadolint:v2.15.1-debian
#           macOS:     cat Dockerfile.alpine | docker run --rm --interactive hadolint/hadolint:v2.15.1-debian
#
#           docker debug juergenzimmermann/buch:2026.10.1-alpine
#           docker network ls

# https://docs.docker.com/engine/reference/builder/#syntax
# https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md
# https://hub.docker.com/r/docker/dockerfile
# https://docs.docker.com/build/building/multi-stage
# https://github.com/textbook/starter-kit/blob/main/Dockerfile
# https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker
# https://cheatsheetseries.owasp.org/cheatsheets/NodeJS_Docker_Cheat_Sheet.html

ARG NODE_VERSION=26.7.0 \
    ALPINE_VERSION=3.24

# ---------------------------------------------------------------------------------------
# S t a g e   d i s t
# ---------------------------------------------------------------------------------------
FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS dist

ARG NODE_UID=1000 \
    NODE_GID=1000

RUN <<EOF
  # https://explainshell.com/explain?cmd=set+-eux
  set -eux

  # apk = Alpine Package Keeper
  # https://wiki.alpinelinux.org/wiki/Alpine_Package_Keeper
  # https://docs.alpinelinux.org/user-handbook/0.1a/Working/apk.html
  # Die "Package Index"-Dateien neu synchronisieren
  apk update
  # Die neuesten Versionen der bereits installierten Packages installieren
  apk upgrade

  npm r -g pnpm
  npm i -g pnpm@12.0.0-rc.7

  # Python evtl. fuer pg
  # https://dl-cdn.alpinelinux.org/alpine/v3.23/main/x86_64
  # https://dl-cdn.alpinelinux.org/alpine/v3.23/community/x86_64
  # https://pkgs.alpinelinux.org/package/v3.23/main/x86_64/python3
  # https://pkgs.alpinelinux.org/package/v3.23/community/x86_64/py3-pip
  # https://pkgs.alpinelinux.org/package/v3.23/main/x86_64/make
  # https://pkgs.alpinelinux.org/package/v3.23/main/x86_64/gcc
  # https://pkgs.alpinelinux.org/package/v3.23/main/x86_64/g++
  # https://pkgs.alpinelinux.org/package/v3.23/main/x86_64/build-base
  # apk info python3
  apk add --update --no-cache python3=3.14.7-r1 make=4.4.1-r4 gcc=15.2.0-r5 g++=15.2.0-r5 build-base=0.5-r4
  ln -sf python3 /usr/bin/python

EOF

USER ${NODE_UID}:${NODE_GID}

WORKDIR /home/node

# Sonst "lock"-Konflikte mit Stage "dependencies" (s.u.)
COPY --chown=${NODE_UID}:${NODE_GID} pnpm-lock.yaml pnpm-workspace.yaml ./
# fuer script "posttsc" in package.json
COPY --chown=${NODE_UID}:${NODE_GID} scripts/copy-resources.mts ./scripts/

# https://docs.docker.com/engine/reference/builder/#run---mounttypebind
RUN --mount=type=bind,source=package.json,target=package.json \
  --mount=type=bind,source=tsconfig.json,target=tsconfig.json \
  --mount=type=bind,source=src,target=src \
  --mount=type=cache,target=/root/.pnpm <<EOF

  set -eux
  pnpm i
  pnpm run tsc
EOF

# ------------------------------------------------------------------------------
# S t a g e   d e p e n d e n c i e s
# ------------------------------------------------------------------------------
FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS dependencies

ARG NODE_UID=1000 \
    NODE_GID=1000

ENV PYTHONUNBUFFERED=1

RUN <<EOF
  set -eux
  apk update
  apk upgrade

  apk add --update --no-cache python3=3.14.7-r1 make=4.4.1-r4 gcc=15.2.0-r5 g++=15.2.0-r5 build-base=0.5-r4
  ln -sf python3 /usr/bin/python

  npm i -g pnpm@12.0.0-rc.7
EOF

USER ${NODE_UID}:${NODE_GID}

WORKDIR /home/node

RUN --mount=type=bind,source=package.json,target=package.json \
  --mount=type=bind,source=pnpm-lock.yaml,target=pnpm-lock.yaml \
  --mount=type=bind,source=pnpm-workspace.yaml,target=pnpm-workspace.yaml \
  --mount=type=cache,target=/root/.pnpm <<EOF

  set -eux
  PATH=/opt/pnpm/bin:$PATH
  pnpm i --prod --frozen-lockfile
EOF

# ------------------------------------------------------------------------------
# S t a g e   f i n a l
# ------------------------------------------------------------------------------
FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS final

ARG NODE_UID=1000 \
    NODE_GID=1000

RUN <<EOF
  set -eux

  apk update
  apk upgrade

  # https://pkgs.alpinelinux.org/package/v3.24/main/x86_64/wget
  apk add --update --no-cache wget=1.25.0-r3
  apk cache clean
  rm -rf /tmp/*
EOF

WORKDIR /opt/app

# ADD hat mehr Funktionalitaet als COPY, z.B. auch Download von externen Dateien
COPY --from=dist --chown=${NODE_UID}:${NODE_GID} /home/node/dist/src ./dist/src
COPY --chown=${NODE_UID}:${NODE_GID} package.json .env ./
COPY --from=dependencies --chown=${NODE_UID}:${NODE_GID} /home/node/node_modules ./node_modules

USER ${NODE_UID}:${NODE_GID}

EXPOSE 3000
EXPOSE 3030

HEALTHCHECK --interval=30s --timeout=3s --retries=1 \
  CMD ["sh", "-c", "wget -qO- --no-check-certificate https://localhost:3000/health/readiness/ | grep ok || exit 1"]

# Anzeige bei "docker inspect ..."
# https://specs.opencontainers.org/image-spec/annotations
# https://spdx.org/licenses
# MAINTAINER ist deprecated https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
LABEL org.opencontainers.image.title="buch" \
  org.opencontainers.image.description="Appserver buch mit Basis-Image Alpine" \
  org.opencontainers.image.version="2026.10.1-alpine" \
  org.opencontainers.image.licenses="GPL-3.0-or-later" \
  org.opencontainers.image.authors="Juergen.Zimmermann@h-ka.de"

# Bei CMD statt ENTRYPOINT kann das Kommando bei "docker run ..." ueberschrieben werden
# "Array Syntax" damit auch <Strg>C funktioniert
ENTRYPOINT ["/usr/local/bin/node", "--env-file=.env", "dist/src/index.mjs"]
