// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// oxlint-disable-next-line import/no-unassigned-import
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import process from 'node:process';

// oxlint-disable-next-line import/no-default-export
export default defineConfig({
    schema: 'prisma/schema.prisma',
    // migrations: {
    //     path: 'prisma/migrations',
    // },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
});
