# suppress inspection "UnusedProperty" for whole file
# Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# https://docs.sonarqube.org/latest/analysis/analysis-parameters

sonar.projectKey = buch
sonar.projectDescription = Beispiel fuer Software Engineering
sonar.projectVersion = 2024.04.0

sonar.scm.disabled = true
# sonar.scm.provider = git

sonar.sources = src
sonar.tests = __tests__

# SonarQube Token von http://localhost:9000: MyAccount > Security
sonar.token = sqa_c5b304695772edad15ad83c7cd2a2d8eafd67fc3

sonar.javascript.environments = node
sonar.exclusions = node_modules/**,.extras/**,.scannerwork/*,.vscode/*,coverage/**,dist/*,log/*
sonar.javascript.lcov.reportPaths = ./coverage/lcov.info
