# Copyright (C) 2026 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker volume create kc_data
#           docker volume create kc_tls
#
#           docker compose -f compose.bash.yml up
#           docker compose exec keycloak bash
#               cp /run/secrets/* /opt/keycloak/tls
#               chown -R nonroot:nonroot /opt/keycloak/tls
#               exit
#           docker compose -f compose.bash.yml down
#
#           docker volume inspect kc_tls
#               Mountpoint: /var/lib/docker/volumes/kc_tls/_data

services:
  keycloak:
    image: dhi.io/keycloak:26.5.2-debian13
    entrypoint: ["/bin/bash", "-c", "echo 'Container (mit Keycloak-Image) ist als Bash gestartet.' && sleep infinity"]
    volumes:
      - kc_tls:/opt/keycloak/tls
    # /run/secrets
    secrets: [kc_cert, kc_key]
    user: 0:0

secrets:
  kc_cert:
    file: ./certificate.crt
  kc_key:
    file: ./key.pem

volumes:
  kc_tls:
    name: kc_tls
    external: true
